### ISSUE TITLE
Avoid duplicate/copy of photos under protected_media/photos

### ISSUE THREAD

**Issue by vkadam** [hooram/ownphotos-backend#78]
I setup the docker for ownphotos on my Synology nas to explore it. I see that when I started scanning file_system it copied photos from my mounted path `/data` to `/code/protected_media` with unique file names. Is there a way to avoid this copy and refer to existing file instead to save space.

**Comment by thechickenmoo** [comment]
If I'm not mistaken those should be thumbnails and etc. not the whole image itself.

**Comment by partyant** [comment]
@vkadam - there's a little bit more to that than just blind copying. it is in fact transposing (rotating, flipping, etc) the images to match the correct orientation and saves them processed. In the current implementation it also transcodes the images to JPEG with quality setting 75%, so you may also see some significant reduction ton the file sizes (along with the drop in quality).

**Comment by partyant** [comment]
oh and... while I understand this duplication may seem inconvenient - it actually allows for a "proper" rendering of the images in browsers, as well as better isolation of access permissions for multi-tenant environments.

**Comment by vkadam** [comment]
@thechickenmoo thumbnails are stored in separate folder and that size is significantly lower.
@partyant, as you mentioned quality of these images from "photos" folder is degraded compare to original. Currently scanning has processed around 5600 images out of 46k and using around 7GB space :(
Do we have any another option here currently, or may be in future already on your roadmap?

**Comment by partyant** [comment]
@vkadam - this is definitely one feature that deserves to be implemented in the future. However in the current version I haven't seen any options to workaround the image transcoding (I am not an author or maintainer of the project).

In my opinion it would be most useful if the `protected_media` contained the transposed/transcoded versions of the images capped at 2048x2048 px, while using the `/data` to retrieve the originals when requested.
In the front-end by default the 2048x2048 version will be displayed, with a separate button to download the original.

A photo library of 50k images (est 5MB per image) would take about 250 GB of disk space, while the 2048x2048 versions (est 300k per image) would use about 15GB extra. This is just about 6% overhead - perfectly worth the performance improvements that it would bring.

**Comment by hooram** [comment]
I looked into this a little bit yesterday. If we want to not make a copy of the original, one way to go about it is to make nginx serve the original via the x-accel-redirect header. From the backend docker container's point of view, the originals are stored in /data. I modified the nginx.conf to add the following lines

```
location /original {
    internal;
    alias /data;
}
```

And in the class `MediaAccessView` in `api/views.py`, I added some logic that determines whether the request wants a fullsize copy (namely `/api/media/photos/{image_hash}.jpg`) and send a response with x-accel-redirect header to path `/original/{path_to_original}`. This should make it serve the original photo, bypassing the need to actually store the fullsize copy of the original in `/code/protected_media/`, which should bring down the storage overhead quite a bit, like @partyant said. The problem is though, nginx doesn't have permission to view the files, and I don't want to mess with the permissions of the /data directory, as it might need to have some specific permissions involving other software (like nextcloud). 

When I `docker exec -it ownphotos-backend /bin/bash` and `ls -l /data/`, I see the files are owned by 1000:1000. Does anyone know how I can add the `www-data` user to the 1000 group?

**Comment by partyant** [comment]
@hooram - 1000 is an identifier of a group that exists on the host system, this identifier may be different on every system. To add a user `www-data` to that group you have to first create the group  inside of the container `groupadd -g 1000 some-group-name` and  then add the user to it like `usermod -a -G some-group-name www-data`.
This is not sustainable because the group identifiers can be different depending on the file ownership. The reason why the import job can access them is because it runs as `root`, and not as `www-data`.
So the "proper" way to let nginx access the files owned by any other users is to run it as `root`. While this is not the best idea from the security point of view - most risks can be mitigated by mounting the data volume as `read only` (`:ro` suffix).

By the way - these are exactly the issues that I mentioned in my earlier comment about the isolation of access permissions.

One last point - if nginx servers the original images the UX will be affected in the way that "vertical" photos from many cameras will not be rotated properly in a browser, so this option would essentially "download" the image instead of making it viewable on the page.

**Comment by hooram** [comment]
@partyant On your last point - I did implement the necessary changes to let nginx serve the original (by `-v`ing a directory that nginx has read access to to /data), and exactly your point stands - serving a 2048px viewable image that's correctly rotated to the frontend, but make the download button link to the original. I'll look more into running nginx as root, and report back. Really appreciate your feedback!

**Comment by vkadam** [comment]
@hooram @partyant thanks for update.
Regarding changing nginx and adding alias to `/data`, will it stop copying folder during scanning process?
Also for nginx file access, how about accepting environment variable like user id & group id, then starting nginx and ownphotos with that user.
This way user can pass the uid & guid having appropriate access to /data folder.
I have seen same setup done by lots of linuxserver provided docker images. Here is one example, https://hub.docker.com/r/linuxserver/plex#user--group-identifiers.

Also as we are talking about nginx, to save the memory and run one less container, I have started the nginx on frontend container it self. I will recommend of doing it as standard setup if you agrees.

Following was the setup I did for frontend setup in docker-compose.yml (This does not do the user id/ guid setup I mentioned about, this start nginx with root user)
```
ports:
      - "3000:80"
    entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
    command: |
      /bin/bash -c "
      set -eux; 
      apt-get update; 
      apt-get install nginx -y; 
      cp nginx.conf /etc/nginx/nginx.conf; 
      sed -ie 's/user  nginx/user root/g' /etc/nginx/nginx.conf; 
      /etc/init.d/nginx start; 
      ./run.sh";
```
Removed ownphotos-proxy setup completely.
